---
- hosts: prod
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
   -  copy: src="ospatch_15042022.sh" dest="/tmp/"
   -  file: path=/tmp/ospatch_15042022.sh owner=root group=root mode=755
   -  shell: /bin/sh /tmp/ospatch_15042022.sh
   -  command: /sbin/reboot
